version: '3'

services:
  postgres:
    image: "postgres:9.6-alpine"
    container_name: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_SERVER=postgres
      - POSTGRES_DB=library
      - POSTGRES_USER=library
      - POSTGRES_PASSWORD=library

  library:
    build: .
    container_name: library-app
    ports:
      - 8080:8080
    environment:
      - POSTGRES_SERVER=postgres
      - POSTGRES_DB=library
      - POSTGRES_USER=library
      - POSTGRES_PASSWORD=library
    depends_on:
      - postgres

volumes:
  postgres-data: